# command t verify : docker-compose config
# docker-compose -f docker-compose.yml up --build
# docker-compose up -d --build

# version: "3"
# services:
  # api-server:
    # container_name: scrapper-api
    # build:
      # context: api-services
    # links:
      # - rabbitmq


version: "3"
services:
  api1:
    container_name: hazelc-api
    build:
      context: hazy-api-service
    ports:
      - "8089:8089"
