server:
  port: 8080
  servlet:
    context-path: /hz
spring:
  profiles.active: default
  application:
    name: hze-apiserver
logging:
  level:
    root: INFO
    org.springframework.web: INFO

---
spring:
  profiles: default
---
server:
  port: 8088
  servlet:
    context-path: /hzd

spring:
  profiles: dev
  profiles.include: default